
import java.awt.CardLayout;

/*
 * GantiGambar.java
 *
 * Created on December 9, 2021, 12:37 PM
 */



/**
 *
 * @author  HP
 */
public class GantiGambar extends javax.swing.JFrame {

    /** Creates new form GantiGambar */
    public GantiGambar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ronaldo1BT = new javax.swing.JButton();
        ronaldo2BT = new javax.swing.JButton();
        ronaldoBT3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ronaldo1BT.setText("Gambar1");
        ronaldo1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ronaldo1BTActionPerformed(evt);
            }
        });

        ronaldo2BT.setText("Gambar 2");
        ronaldo2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ronaldo2BTActionPerformed(evt);
            }
        });

        ronaldoBT3.setText("Gambar 3");
        ronaldoBT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ronaldoBT3ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, "0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, "1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background3.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, "2\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ronaldo1BT)
                        .addGap(52, 52, 52)
                        .addComponent(ronaldo2BT)
                        .addGap(55, 55, 55)
                        .addComponent(ronaldoBT3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ronaldo1BT)
                    .addComponent(ronaldo2BT)
                    .addComponent(ronaldoBT3))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ronaldo1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ronaldo1BTActionPerformed
// TODO add your handling code here:
    CardLayout cl = (CardLayout) (jPanel1.getLayout());
    cl.show(jPanel1, "0");
}//GEN-LAST:event_ronaldo1BTActionPerformed

private void ronaldo2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ronaldo2BTActionPerformed
// TODO add your handling code here:
    CardLayout cl = (CardLayout) (jPanel1.getLayout());
    cl.show(jPanel1, "1");
}//GEN-LAST:event_ronaldo2BTActionPerformed

private void ronaldoBT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ronaldoBT3ActionPerformed
// TODO add your handling code here:
    CardLayout cl = (CardLayout) (jPanel1.getLayout());
    cl.show(jPanel1, "2");
}//GEN-LAST:event_ronaldoBT3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GantiGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ronaldo1BT;
    private javax.swing.JButton ronaldo2BT;
    private javax.swing.JButton ronaldoBT3;
    // End of variables declaration//GEN-END:variables

}
